name: Math Utility Project (CI included) | © 2025 by luongmike

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'              # Dùng Java 17 tương thích tốt với Groovy 4 và Spock
        distribution: 'temurin'
        cache: maven

    - name: Verify test files exist
      run: ls -R src/test/groovy || echo "No test files found!"

    - name: Run Unit Tests with Spock
      run: mvn test                     # Chạy test Groovy/Spock trong thư mục src/test/groovy

    - name: Build and Package App
      run: mvn package -DskipTests     # Đóng gói .jar sau khi test thành công (không chạy lại test)

    - name: Prepare JAR for Distribution
      run: mkdir staging && cp target/*.jar staging

    - name: Upload JAR as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: cham_em_ngoc_trinh_lay_jar
        path: staging
